baseurl = "/"
languageCode = "fr-FR"
title = ""
baseURL = "https://carole-millot-psychologue.fr"
disableKinds = ["taxonomy", "taxonomyTerm"]

[menu]
  [[menu.main]]
    identifier = "Consulter"
    name = "Pourquoi consulter"
    url = "/pourquoi-consulter/"
    weight = 1

  [[menu.main]]
    name = "Formation"
    url = "/formation/"
    weight = 2

  [[menu.main]]
    name = "Le cabinet"
    url = "/cabinet-de-psychologie/"
    weight = 3
